### PR TITLE
Don't panic if driverRows.Next is called after Close

### LINKED ISSUE #65: Panic: runtime error: index out of range in driverRows.Next
I'm hitting a panic that I reproduce pretty well, but not always, it sometimes panics and sometimes doesn't.

I'm using a pretty simple query: `SELECT 1, NULL, 'abc'"`, but I'm not sure if it's relevant.

The relevant part of the backtrace:

```
panic: runtime error: index out of range [1] with length 1

goroutine 125 [running]:
github.com/trinodb/trino-go-client/trino.(*driverRows).Next(0x14000708160, {0x140000aa3f0, 0x9, 0x10667fbb0?})
        /Users/thomas/go/pkg/mod/github.com/trinodb/trino-go-client@v0.308.0/trino/trino.go:1028 +0x2a0
```

After that it's my code calling `trino.driverRows.Next` directly.

Code where the panic happens: https://github.com/trinodb/trino-go-client/blob/565ca64bac1a1fc78d2413736a4abf6d9d38e85c/trino/trino.go#L1028

This is the state of `trino.driverRows`:

```
// First call to trino.driverRows.Next (Ok):
&{
	ctx:0x14000117980 
	stmt:0x140001153e0 
	queryID:20230104_135631_01766_ysbyr 
	nextURI:https://localhost:8443/v1/statement/queued/20230104_135631_01766_ysbyr/y235c9529065f1ef1da71af639ccea62d7e95fe9e/1 
	err:<nil> 
	rowindex:0 
	columns:[_col0 _col1 _col2] 
	coltype:[0x140001a67e0 0x140001a68c0 0x140001a6930] 
	data:[[1 <nil> abc]] 
	rowsAffected:0 
	statsCh:<nil> 
	doneCh:0x1400056e360
}

// Second call (panics):
&{
	ctx:0x14000117980 
	stmt:0x140001153e0 
	queryID:20230104_135631_01766_ysbyr 
	nextURI:https://localhost:8443/v1/statement/queued/20230104_135631_01766_ysbyr/y235c9529065f1ef1da71af639ccea62d7e95fe9e/1 
	err:<nil> 
	rowindex:1 
	columns:[_col0 _col1 _col2] 
	coltype:[0x140001a67e0 0x140001a68c0 0x140001a6930] 
	data:[[1 <nil> abc]] 
	rowsAffected:0 
	statsCh:<nil> 
	doneCh:0x1400056e360
}
```

I think the following line is incorrect: https://github.com/trinodb/trino-go-client/blob/565ca64bac1a1fc78d2413736a4abf6d9d38e85c/trino/trino.go#L1010

~~I think `>=` should be changed to `>` since indexing is zero based.~~
~~But what I can't figure out why the current code works sometimes, but panics in the next test run...~~ Incorrect.

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
Previously this would panic with an index out of range error. Which was misleading as the indexing itself wasn't the problem. The problem was that fetch returns a `nil` error if the error channel was closed, which led the `Next` function to believe there was more data ready to be processed, but this was not the case.

The error channel is only closed if Close is called on `driverRows` or `driverStmt`, so this panic was caused by a premature closing of the rows or statement, but that hard to tell from the panic message.

This commit changes removes the panic and instead returns an `io.EOF` error if we detect that fetch was called on a closed statement or rows.

Closes #65.

### CODE REVIEW

File: trino/integration_test.go [hunk 1]
```diff
@@ -527,6 +529,36 @@ func TestIntegrationQueryParametersSelect(t *testing.T) {
...
+	defer rows.Close()
+
+	stmt.Close() // NOTE: the important bit.
+
+	var result driver.Value
+	if err := rows.Next([]driver.Value{result}); err != nil {
+		t.Fatalf("unexpected result: %+v", err)
+	}
+	if err := rows.Next([]driver.Value{result}); err != io.EOF {
+		t.Fatalf("unexpected result: %+v", err)
```
Comment (nineinchnick) [inline trino/integration_test.go:558]: The error message should say that `io.EOF` was expected.

File: trino/integration_test.go [hunk 2]
```diff
@@ -527,6 +529,36 @@ func TestIntegrationQueryParametersSelect(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("Failed running query: %v", err)
+	}
+	defer rows.Close()
+
+	stmt.Close() // NOTE: the important bit.
+
+	var result driver.Value
+	if err := rows.Next([]driver.Value{result}); err != nil {
+		t.Fatalf("unexpected result: %+v", err)
```
Comment (nineinchnick) [inline trino/integration_test.go:555]: The error message should say that no error was expected.

File: trino/trino.go [hunk 3]
```diff
@@ -1139,7 +1139,14 @@ func (qr *driverRows) fetch() error {
 				return nil
 			}
 		case err = <-qr.stmt.errors:
-			if err == context.Canceled {
+			if err == nil {
+				// Channel was closed, which means the statement
+				// or rows were closed.
+				// Previously this would panic with an index out
+				// of bounds, now we return io.EOF, see
+				// https://github.com/trinodb/trino-go-client/issues/65.
```
Comment (nineinchnick) [inline trino/trino.go:1147]: Don't refer to the past, this is what git commit history is for.

**Review by nineinchnick — APPROVED** [review]
LGTM except these two nitpicks.

**Comment by Thomasdezeeuw** [comment]
Done, though you might want to squash the commits. As for the CLI my company, Slight, should have signed it. But I'll ask internally what the status of that is.

File: trino/trino.go (hunk 3 above)
Comment (nineinchnick) [reply trino/trino.go]: You still have a comment here that refers to past behavior, it is not needed.

Comment (Thomasdezeeuw) [reply trino/trino.go]: I though you were only referring to the linking of the issue, removed the second part of the comment entirely.

**Comment by Thomasdezeeuw** [comment]
> > Done, though you might want to squash the commits. As for the CLI my company, Slight, should have signed it. But I'll ask internally what the status of that is.
> 
> Please squash commits yourself. The PR is small so it's easy to track requested changes.

Done.

> The CLAs gets processed every two weeks or so. I hope you don't mind if this PR will stay open for a bit. Thanks a lot for the contribution!

No problem.

**Comment by Thomasdezeeuw** [comment]
Alright, CLA signed and approved.

**Comment by nineinchnick** [comment]
@clabot check

**Comment by nineinchnick** [comment]
@cla-bot check

**Comment by nineinchnick** [comment]
@losipiuk PTAL, it should be ready to be merged.
